version: '3.8'
services:
  go_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: "bind"
        source: .
        target: /go/src/app
    ports:
      - "8080:8080"
